# Suricata DDoS detection rules

- alert:
    action: alert
    proto: tcp
    src_ip: any
    src_port: any
    dest_ip: any
    dest_port: 80
    msg: "SYN Flood Detected"
    flags: "S"
    sid: 2000001

- alert:
    action: alert
    proto: tcp
    src_ip: any
    src_port: any
    dest_ip: any
    dest_port: 80
    msg: "HTTP GET Flood Detected"
    flow: to_server, established
    content: "GET"
    threshold: type threshold, track by_src, count 50, seconds 10
    sid: 2000002
